### ISSUE TITLE
[master | 1.8.0] Recent user posts receiving home posts

### ISSUE THREAD

**Issue by MikeDev101** [meower-media-co/Meower-Svelte#190]
![image](https://github.com/meower-media-co/Meower-Svelte/assets/12957745/1dda7465-f351-4330-9923-af894375c9be)

When navigating to one's recent posts page, new home posts appear in the message view.

**Comment by Mystery9-6** [comment]
lordpenguin admin abuse real!!!1!1111!11

**Comment by derpygamer2142** [comment]
hey look mom, i'm on meower-svelte 1.8 issue #190!

**Comment by tnix100** [comment]
> ![image](https://user-images.githubusercontent.com/12957745/280150030-1dda7465-f351-4330-9923-af894375c9be.png)
> 
> When navigating to one's recent posts page, new home posts appear in the message view.

I saw this bug the other day when looking at the admin view for posts, I forgot that setting the `postOrigin` attribute on the `PostsList` component causes new posts to be added and typing indicators to show.

**Comment by tnix100** [comment]
Should be fixed as of https://github.com/meower-media-co/Meower-Svelte/commit/c94ee41f59617ef0666cb7f497958c63c05d6423

It seems that GH has auto-closed this due to my commit, feel free to re-open if you want.

**Comment by OneShot-Niko** [comment]
> I saw this bug the other day when looking at the admin view for posts, I forgot that setting the `postOrigin` attribute on the `PostsList` component causes new posts to be added and typing indicators to show.

Don't wanna make a dupe - Could this get reopened by any chance?
The bug still appears to occur.

**Comment by zzthebooplister** [comment]
me: you admin abuse
lp: **_nuh uh_**

**Comment by CST1229** [comment]
> The bug still appears to occur:

Does it still occur on develop? https://develop.meower-svelte.pages.dev

**Comment by tnix100** [comment]
Yeah, this bug is fixed in develop. It'll eventually be moved into master (app.meower.org).

**Comment by OneShot-Niko** [comment]
> Does it still occur on develop? [develop.meower-svelte.pages.dev](https://develop.meower-svelte.pages.dev)

Nope

> Yeah, this bug is fixed in develop. It'll eventually be moved into master (app.meower.org).

Ah, my apologies then.

**Comment by CST1229** [comment]
IMO issues should be closed when they are fixed *on develop*; it's the default branch and master is more of a stable/release branch.
