### ISSUE TITLE
[master | 1.9.0] 1.9 is unfinished and extremely unstable

### ISSUE THREAD

**Issue by delusionsGH** [meower-media-co/Meower-Svelte#250]
## Expected behavior

A finished and stable build of Meower Svelte v1.9.0, with everything tested before being put in.
## Current behavior

https://github.com/meower-media-co/Meower-Svelte/commit/02d4f8f2089bf668aa961ed5142a8a27ec7beb56#commitcomment-144251906
## Possible solution

REVERT 1.9.0 AND DO _**NOT**_ PUSH IT UNTIL IT IS READY FOR PRODUCTION!
## Steps to reproduce

1. Open Meower Svelte
2. Try uploading, logging in, etc.
## Screenshots / Logs

See https://github.com/meower-media-co/Meower-Svelte/commit/02d4f8f2089bf668aa961ed5142a8a27ec7beb56#commitcomment-144251906
## Platform info

**Meower Client**
- Meower Client Version + Build Date: Svelte v1.9.0 - 15/07/2024 (DD/MM/YYYY)

**Desktop**
 - OS: Windows 11
 - Version: 23H2
 - RAM: 16GB
 - Storage: 256GB SSD + 500GB HDD
 - CPU Architecture: x64
 
## Did I read the instructions before making this bug report?

**I have read the instructions.**

**Comment by delusionsGH** [comment]
Please push https://github.com/meower-media-co/Meower-Svelte/pull/249
This update is not finished, and should be reverted ASAP

**Comment by Bloctans** [comment]
everything mentioned aside from the login bug which i've yet to fix (as i dont know how the new auth system works) has been fixed in #251

**Comment by delusionsGH** [comment]
> everything mentioned aside from the login bug which i've yet to fix (as i dont know how the new auth system works) has been fixed in #251

settings is STILL incomplete, the dropdown still has an unnecessary about button, replies are still bad, deleting posts with attachments is still broken, markdown is still bad

**Comment by Bloctans** [comment]
> > everything mentioned aside from the login bug which i've yet to fix (as i dont know how the new auth system works) has been fixed in #251
> 
> settings is STILL incomplete, the dropdown still has an unnecessary about button, replies are still bad, deleting posts with attachments is still broken, markdown is still bad

ill fix the settings issue, replies are going to stay the same (read my message in the pr), ill fix the deleting posts thing, and idk whats wrong about markdown aside from the error thing which ill fix too

**Comment by delusionsGH** [comment]
revert has been merged, closing.
